"""
Lead Model
==========

Real-world business context:
  A "lead" is a potential car buyer whose phone number the dealership has.
  Sources:
    - Walk-in inquiry form (name + phone collected at showroom)
    - Website inquiry / test drive booking
    - Trade show / auto expo contact list
    - Purchased bulk lead lists (CSV import)
    - Referral from existing customer
    - Exchange enquiry (wants to trade old car)

  The AI caller agent calls each lead, introduces the campaign offer,
  answers questions using the KB, and qualifies interest level.

  Lead lifecycle:
    new → called → interested → follow_up → converted | not_interested | unreachable

  Phone validation:
    - Indian numbers: 10 digits, starts with 6-9
    - Stored in E.164 format: +91XXXXXXXXXX
    - Duplicate detection: same phone within same dealership
"""

import uuid
from sqlalchemy import Column, String, TIMESTAMP, ForeignKey, Text, Integer, Boolean, Numeric
from sqlalchemy.dialects.postgresql import UUID
from app.core.database import Base


class Lead(Base):
    __tablename__ = "leads"

    lead_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # ── Ownership ─────────────────────────────────────────────────────────────
    dealership_id = Column(
        UUID(as_uuid=True),
        ForeignKey("dealerships.dealership_id"),
        nullable=False,
        index=True
    )
    campaign_id = Column(
        UUID(as_uuid=True),
        ForeignKey("campaigns.campaign_id"),
        nullable=False,
        index=True
    )

    # ── Contact identity ──────────────────────────────────────────────────────
    name = Column(String(150), nullable=False)
    phone = Column(String(20), nullable=False)           # E.164: +91XXXXXXXXXX
    alternate_phone = Column(String(20), nullable=True)
    email = Column(String(255), nullable=True)

    # ── Car interest ──────────────────────────────────────────────────────────
    # What model they're interested in (free text — may not match a car_model exactly)
    car_interest = Column(String(150), nullable=True)    # e.g. "Brezza ZXi+"
    # Specific variant preference if known
    variant_preference = Column(String(100), nullable=True)
    # Fuel preference
    fuel_preference = Column(String(30), nullable=True)  # Petrol | Diesel | CNG

    # ── Budget ────────────────────────────────────────────────────────────────
    budget_min = Column(Numeric(12, 2), nullable=True)   # e.g. 800000
    budget_max = Column(Numeric(12, 2), nullable=True)   # e.g. 1200000
    emi_preferred = Column(Boolean, nullable=True)        # wants EMI or cash

    # ── Current vehicle ───────────────────────────────────────────────────────
    current_car = Column(String(150), nullable=True)     # e.g. "Maruti Swift 2019"
    wants_exchange = Column(Boolean, nullable=True)      # trade-in interest

    # ── Lead source ───────────────────────────────────────────────────────────
    # walk_in | website | csv_import | referral | auto_expo | manual
    source = Column(String(50), nullable=False, default="manual")
    source_detail = Column(String(255), nullable=True)   # e.g. CSV filename, referrer name

    # ── Call status lifecycle ─────────────────────────────────────────────────
    # new → called → interested → follow_up → converted | not_interested | unreachable | dnc
    call_status = Column(String(30), nullable=False, default="new")

    # ── Interest qualification ────────────────────────────────────────────────
    # hot | warm | cold (set by AI after call or manually by agent)
    interest_level = Column(String(20), nullable=True)

    # ── Call tracking ─────────────────────────────────────────────────────────
    call_attempts = Column(Integer, nullable=False, default=0)
    last_called_at = Column(TIMESTAMP, nullable=True)
    next_followup_at = Column(TIMESTAMP, nullable=True)  # scheduled follow-up time
    do_not_call = Column(Boolean, nullable=False, default=False)  # DNC registry

    # ── AI call notes ─────────────────────────────────────────────────────────
    # Summary generated by AI after call: what customer asked, what was promised
    call_summary = Column(Text, nullable=True)
    # Internal notes by sales rep
    agent_notes = Column(Text, nullable=True)

    # ── Duplicate tracking ────────────────────────────────────────────────────
    # If this lead was imported and matched an existing lead, link to original
    duplicate_of = Column(
        UUID(as_uuid=True),
        ForeignKey("leads.lead_id"),
        nullable=True
    )
    is_duplicate = Column(Boolean, nullable=False, default=False)

    # ── Audit ─────────────────────────────────────────────────────────────────
    added_by = Column(UUID(as_uuid=True), ForeignKey("users.user_id"), nullable=True)
    created_at = Column(TIMESTAMP, nullable=False)
    updated_at = Column(TIMESTAMP, nullable=False)
    deleted_at = Column(TIMESTAMP, nullable=True)